version: 2.1
executors:
  my-executor:
    docker:
      - image: circleci/python:3.6.8
        environment:
          PIPENV_VENV_IN_PROJECT: true
    working_directory: ~/CircleCIDeploySample

jobs:
  setup:
    executor: my-executor
    steps:
      - checkout
      - restore_cache:
          key: CircleCIDeploySample-v2-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: install
          command: |
            pip install pipenv
            pipenv install
      - save_cache:
          paths:
            - ".venv"
          key: CircleCIDeploySample-v2-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
  build:
    executor: my-executor
    steps:
      - checkout
      - restore_cache:
          key: CircleCIDeploySample-v2-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: sam-build
          command: |
            source .venv/bin/activate
            aws --version
  deploy:
    executor: my-executor
    steps:
      - checkout
      - restore_cache:
          key: CircleCIDeploySample-v2-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: sam-deploy
          command: |
            source .venv/bin/activate
            sam --version

workflows:
  version: 2.1
  CircleCIDeploySample-deploy-workflow:
    jobs:
      - setup:
          filters:
            branches:
              only:
                - master
                - develop
      - build:
          requires:
            - setup
      - deploy:
          requires:
            - build
