version: 2.1
executors:
  my-executor:
    docker:
      - image: circleci/python:3.6.8
        environment:
          PIPENV_VENV_IN_PROJECT: true
    working_directory: ~/CircleCIDeploySample

commands:
  restore:
    steps:
      - restore_cache:
          key: CircleCIDeploySample-v3-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
  save:
    steps:
      - save_cache:
          paths:
            - ".venv"
          key: CircleCIDeploySample-v3-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

jobs:
  setup:
    executor: my-executor
    steps:
      - checkout
      - restore
      - run:
          name: install
          command: |
            pip install pipenv
            pipenv install
      - save
  build:
    executor: my-executor
    parameters:
      system-env:
        type: enum
        enum: ["prod", "dev"]
        default: "dev"
    steps:
      - checkout
      - restore
      - run:
          name: sam-build
          command: |
            source .venv/bin/activate
            aws --version
            echo << parameters.system-env >>
  deploy:
    executor: my-executor
    parameters:
      system-env:
        type: enum
        enum: ["prod", "dev"]
        default: "dev"
    steps:
      - checkout
      - restore
      - run:
          name: sam-deploy
          command: |
            source .venv/bin/activate
            sam --version
            echo << parameters.system-env >>

workflows:
  version: 2.1
  CircleCIDeploySample-deploy-workflow:
    jobs:
      - setup:
          filters:
            branches:
              only:
                - master
                - develop
      - build:
          system-env: dev
          requires:
            - setup
      - deploy:
          system-env: dev
          requires:
            - build
